name: ra_app
description: Une application Flutter avec Google Maps centrée sur Tanger
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^5.1.0
  url_launcher: ^6.2.4
  # panorama: ^0.4.0  # Temporarily commented out due to namespace issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/panoramas/
    - assets/images/ 